@extends('theme::layouts.1col')
@section('title', 'Security Classification')
@section('content')
<h1 class="multiline">Security classification <span class="sub">{{ $resource->title ?? '' }}</span></h1>
@include('theme::partials.alerts')
<section id="content"><div class="card mb-4"><div class="card-header bg-light d-flex justify-content-between align-items-center"><h5 class="mb-0"><i class="bi bi-shield-lock me-2"></i>Security Classification</h5></div><div class="card-body">@if($classification ?? null)<div class="row"><div class="col-md-6 mb-3"><label class="form-label text-muted small">Classification Level</label><p class="mb-0"><span class="badge fs-6" style="background-color:{{ $classification->classification_color ?? $classification->color ?? '#666' }};">{{ $classification->classification_name ?? $classification->name ?? '' }}</span></p></div><div class="col-md-6 mb-3"><label class="form-label text-muted small">Classification Date</label><p class="mb-0">{{ ($classification->classified_at ?? null) ? date('F j, Y', strtotime($classification->classified_at)) : '-' }}</p></div>@if($classification->reason ?? null)<div class="col-12 mb-3"><label class="form-label text-muted small">Classification Reason</label><p class="mb-0">{{ $classification->reason }}</p></div>@endif</div>@else<div class="text-center py-4"><h5>This record is publicly accessible</h5><p class="text-muted">No security classification has been applied.</p></div>@endif</div></div>
@if(!empty($history) && $history->isNotEmpty())<div class="card"><div class="card-header bg-light"><h5 class="mb-0"><i class="bi bi-clock-history me-2"></i>Classification History</h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Date</th><th>Action</th><th>From</th><th>To</th><th>By</th><th>Reason</th></tr></thead><tbody>@foreach($history as $record)<tr><td>{{ date('Y-m-d H:i', strtotime($record->created_at)) }}</td><td><span class="badge bg-info">{{ ucfirst($record->action ?? '') }}</span></td><td>{{ $record->previous_name ?? '-' }}</td><td>{{ $record->new_name ?? '-' }}</td><td>{{ $record->changed_by_username ?? 'System' }}</td><td>{{ $record->reason ?? '-' }}</td></tr>@endforeach</tbody></table></div></div></div>@endif
</section>
@endsection
