@extends('theme::layouts.1col')
@section('title', 'User Clearance: ' . e($targetUser->username ?? ''))
@section('content')
<h1><i class="bi bi-shield-check"></i> User Clearance: {{ e($targetUser->username ?? '') }}</h1>
<div class="mb-3"><a href="{{ route('acl.security-index') }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-arrow-left"></i> Back</a></div>
<div class="row"><div class="col-md-8">
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Current Clearance</h5></div><div class="card-body">@if($clearance ?? null)<div class="row"><div class="col-md-6"><p><strong>Level:</strong><br><span class="badge fs-5" style="background-color:{{ $clearance->classification_color ?? '#666' }}">{{ e($clearance->classification_name ?? '') }}</span></p><p><strong>Granted:</strong><br>{{ ($clearance->granted_at ?? null) ? date('M j, Y', strtotime($clearance->granted_at)) : '-' }}</p></div><div class="col-md-6"><p><strong>Expires:</strong><br>{{ ($clearance->expires_at ?? null) ? date('M j, Y', strtotime($clearance->expires_at)) : 'No expiry' }}</p></div></div>@else<p class="text-muted">No active clearance.</p>@endif</div></div>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">{{ ($clearance ?? null) ? 'Update Clearance' : 'Grant Clearance' }}</h5></div><div class="card-body"><form action="{{ route('acl.set-clearance') }}" method="post">@csrf<input type="hidden" name="user_id" value="{{ $targetUser->id }}"><div class="row"><div class="col-md-6"><div class="mb-3"><label class="form-label">Clearance Level *</label><select name="classification_id" class="form-select" required>@foreach($classifications ?? [] as $level)<option value="{{ $level->id }}" {{ ($clearance && ($clearance->classification_id ?? null) == $level->id) ? 'selected' : '' }}>{{ e($level->name) }}</option>@endforeach</select></div></div><div class="col-md-6"><div class="mb-3"><label class="form-label">Expiry Date</label><input type="date" name="expiry_date" class="form-control"></div></div></div><button type="submit" class="btn btn-primary">Save Clearance</button></form></div></div>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Compartment Access</h5></div><div class="card-body">@if(empty($compartments) || (is_countable($compartments) && count($compartments) === 0))<p class="text-muted">No compartment access granted.</p>@else<table class="table table-sm"><thead><tr><th>Compartment</th><th>Granted</th><th>Expires</th></tr></thead><tbody>@foreach($compartments as $comp)<tr><td><strong>{{ e($comp->code ?? '') }}</strong> - {{ e($comp->name ?? '') }}</td><td>{{ $comp->granted_date ?? '' }}</td><td>{{ $comp->expiry_date ?? '-' }}</td></tr>@endforeach</tbody></table>@endif</div></div>
</div><div class="col-md-4"><div class="card"><div class="card-header"><h5 class="mb-0">User Information</h5></div><div class="card-body"><p><strong>Username:</strong><br>{{ e($targetUser->username ?? '') }}</p><p><strong>Email:</strong><br>{{ e($targetUser->email ?? '') }}</p></div></div></div></div>
@endsection
