@extends('theme::layouts.1col')
@section('title', 'User Clearance - ' . e($targetUser->username ?? ''))
@section('content')
<div class="container mt-4"><div class="row"><div class="col-lg-10 mx-auto">
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li><li class="breadcrumb-item"><a href="{{ route('acl.security-index') }}">Security Clearances</a></li><li class="breadcrumb-item active">{{ e($targetUser->username ?? '') }}</li></ol></nav>
@include('theme::partials.alerts')
<div class="row"><div class="col-md-4 mb-4"><div class="card"><div class="card-header bg-dark text-white"><h5 class="mb-0"><i class="bi bi-person me-2"></i>User Profile</h5></div><div class="card-body text-center"><h4>{{ e($targetUser->username ?? '') }}</h4><p class="text-muted">{{ e($targetUser->email ?? '') }}</p>@if($clearance ?? null)<span class="badge bg-{{ ($clearance->classification_level ?? 0) >= 4 ? 'danger' : (($clearance->classification_level ?? 0) >= 2 ? 'warning' : 'success') }} fs-5 mb-2">{{ e($clearance->classification_name ?? '') }}</span>@else<span class="badge bg-secondary fs-5">No Clearance</span>@endif</div><div class="card-footer"><button class="btn btn-success w-100" data-bs-toggle="modal" data-bs-target="#grantModal">{{ ($clearance ?? null) ? 'Change Clearance' : 'Grant Clearance' }}</button></div></div></div>
<div class="col-md-8"><div class="card mb-4"><div class="card-header bg-success text-white"><h5 class="mb-0"><i class="bi bi-folder me-2"></i>Object Access Grants</h5></div><div class="card-body p-0">@if(empty($accessGrants) || (is_countable($accessGrants) && count($accessGrants) === 0))<div class="p-4 text-center text-muted"><p class="mb-0">No specific object access grants.</p></div>@else<div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>Object</th><th>Access</th><th>Granted</th></tr></thead><tbody>@foreach($accessGrants as $grant)<tr><td><strong>{{ e($grant->object_title ?? 'Unknown') }}</strong></td><td><span class="badge bg-success">{{ ucfirst($grant->access_level ?? '') }}</span></td><td>{{ ($grant->granted_at ?? null) ? date('M j, Y', strtotime($grant->granted_at)) : '-' }}</td></tr>@endforeach</tbody></table></div>@endif</div></div>
<div class="card"><div class="card-header"><h5 class="mb-0"><i class="bi bi-clock-history me-2"></i>Clearance History</h5></div><div class="card-body p-0">@if(empty($history) || (is_countable($history) && count($history) === 0))<div class="p-4 text-center text-muted"><p class="mb-0">No clearance history.</p></div>@else<ul class="list-group list-group-flush">@foreach($history as $entry)<li class="list-group-item"><div class="d-flex justify-content-between align-items-center"><div><span class="badge bg-{{ ($entry->action ?? '') === 'granted' ? 'success' : (($entry->action ?? '') === 'revoked' ? 'danger' : 'info') }} me-2">{{ ucfirst($entry->action ?? '') }}</span>@if($entry->classification_name ?? null)<strong>{{ e($entry->classification_name) }}</strong>@endif</div><small class="text-muted">{{ ($entry->created_at ?? null) ? date('M j, Y H:i', strtotime($entry->created_at)) : '' }}</small></div></li>@endforeach</ul>@endif</div></div></div></div>
</div></div></div>
<div class="modal fade" id="grantModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" action="{{ route('acl.set-clearance') }}">@csrf<div class="modal-header bg-success text-white"><h5 class="modal-title">Grant Security Clearance</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="user_id" value="{{ $targetUser->id ?? '' }}"><p>Granting clearance to: <strong>{{ e($targetUser->username ?? '') }}</strong></p><div class="mb-3"><label class="form-label">Clearance Level</label><select class="form-select" name="classification_id" required><option value="0">-- Revoke --</option>@foreach($classifications ?? [] as $c)<option value="{{ $c->id }}">{{ e($c->name) }} (Level {{ $c->level }})</option>@endforeach</select></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-success">Save</button></div></form></div></div></div>
@endsection
