@extends('theme::layouts.1col')
@section('title', 'Security Access Requests')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('settings.index') }}">Admin</a></li><li class="breadcrumb-item"><a href="{{ route('acl.groups') }}">ACL</a></li><li class="breadcrumb-item active">Access Requests</li></ol></nav>
<div class="d-flex justify-content-between align-items-center mb-4"><h2><i class="bi bi-key me-2"></i>Security Access Requests</h2><a href="{{ route('acl.groups') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Back to ACL</a></div>
<ul class="nav nav-tabs mb-4">
    <li class="nav-item"><a class="nav-link {{ $status === 'pending' ? 'active' : '' }}" href="{{ route('acl.access-requests', ['status' => 'pending']) }}">Pending</a></li>
    <li class="nav-item"><a class="nav-link {{ $status === 'approved' ? 'active' : '' }}" href="{{ route('acl.access-requests', ['status' => 'approved']) }}">Approved</a></li>
    <li class="nav-item"><a class="nav-link {{ $status === 'denied' ? 'active' : '' }}" href="{{ route('acl.access-requests', ['status' => 'denied']) }}">Denied</a></li>
    <li class="nav-item"><a class="nav-link {{ $status === null || $status === '' ? 'active' : '' }}" href="{{ route('acl.access-requests', ['status' => '']) }}">All</a></li>
</ul>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-bordered table-striped table-hover mb-0"><thead><tr><th>User</th><th>Classification</th><th>Request Type</th><th>Justification</th><th class="text-center">Priority</th><th class="text-center">Status</th><th>Requested</th>@if($status === 'pending')<th class="text-end">Actions</th>@endif</tr></thead><tbody>
@forelse($requests as $req)
<tr><td><strong>{{ $req->user_name ?? $req->username ?? '-' }}</strong></td><td>@if($req->classification_name ?? null)<span class="badge" style="background-color:{{ $req->classification_color ?? '#6c757d' }};">{{ $req->classification_name }}</span>@else<span class="text-muted">-</span>@endif</td><td>{{ $req->request_type ?? '-' }}</td><td>{{ \Illuminate\Support\Str::limit($req->justification ?? '', 60) }}</td><td class="text-center">@php $priority = strtolower($req->priority ?? 'normal'); $priorityClass = match($priority) { 'urgent', 'critical' => 'bg-danger', 'high' => 'bg-warning text-dark', 'low' => 'bg-info text-dark', default => 'bg-secondary' }; @endphp<span class="badge {{ $priorityClass }}">{{ ucfirst($req->priority ?? 'Normal') }}</span></td><td class="text-center">@php $reqStatus = strtolower($req->status ?? 'pending'); $statusClass = match($reqStatus) { 'approved' => 'bg-success', 'denied' => 'bg-danger', 'pending' => 'bg-warning text-dark', default => 'bg-secondary' }; @endphp<span class="badge {{ $statusClass }}">{{ ucfirst($req->status ?? 'Pending') }}</span></td><td>{{ $req->created_at ?? '-' }}</td>
@if($status === 'pending')
<td class="text-end"><div class="btn-group btn-group-sm"><button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#approveModal{{ $req->id }}"><i class="bi bi-check"></i></button><button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#denyModal{{ $req->id }}"><i class="bi bi-x"></i></button></div>
<div class="modal fade" id="approveModal{{ $req->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form action="{{ route('acl.review-request', ['id' => $req->id]) }}" method="POST">@csrf<input type="hidden" name="decision" value="approved"><div class="modal-header bg-success text-white"><h5 class="modal-title">Approve Request</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body text-start"><p>Approve request from <strong>{{ $req->user_name ?? $req->username }}</strong>?</p><div class="mb-3"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="3"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-success">Approve</button></div></form></div></div></div>
<div class="modal fade" id="denyModal{{ $req->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form action="{{ route('acl.review-request', ['id' => $req->id]) }}" method="POST">@csrf<input type="hidden" name="decision" value="denied"><div class="modal-header bg-danger text-white"><h5 class="modal-title">Deny Request</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body text-start"><p>Deny request from <strong>{{ $req->user_name ?? $req->username }}</strong>?</p><div class="mb-3"><label class="form-label">Reason</label><textarea name="notes" class="form-control" rows="3"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-danger">Deny</button></div></form></div></div></div>
</td>
@endif
</tr>
@empty
<tr><td colspan="{{ $status === 'pending' ? 8 : 7 }}" class="text-center text-muted py-4">No {{ $status ?? '' }} access requests found.</td></tr>
@endforelse
</tbody></table></div></div></div>
@endsection
