@extends('theme::layouts.1col')
@section('title', 'Access Request Approvers')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('settings.index') }}">Admin</a></li><li class="breadcrumb-item"><a href="{{ route('acl.groups') }}">ACL</a></li><li class="breadcrumb-item active">Approvers</li></ol></nav>
<div class="d-flex justify-content-between align-items-center mb-4"><h2><i class="bi bi-person-check me-2"></i>Access Request Approvers</h2><a href="{{ route('acl.groups') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Back to ACL</a></div>
@include('theme::partials.alerts')
<div class="row"><div class="col-lg-8 mb-4"><div class="card"><div class="card-header bg-primary text-white"><h5 class="mb-0">Current Approvers</h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-bordered table-striped table-hover mb-0"><thead><tr><th>User</th><th>Clearance</th><th>Can Approve</th><th>Email Notify</th><th>Actions</th></tr></thead><tbody>@forelse($approvers as $approver)<tr><td><strong>{{ $approver->display_name ?? $approver->username }}</strong><br><small class="text-muted">{{ $approver->email ?? '' }}</small></td><td>@if($approver->clearance_name)<span class="badge" style="background-color:{{ $approver->clearance_color ?? '#6c757d' }};">{{ $approver->clearance_name }}</span>@else<span class="text-muted">None</span>@endif</td><td>Level {{ $approver->min_classification_level }} - {{ $approver->max_classification_level }}</td><td>{!! $approver->email_notifications ? '<i class="bi bi-check text-success"></i>' : '<i class="bi bi-x text-danger"></i>' !!}</td><td><form action="{{ route('acl.remove-approver', ['id' => $approver->id]) }}" method="POST" onsubmit="return confirm('Remove this approver?');">@csrf<button type="submit" class="btn btn-sm btn-outline-danger"><i class="bi bi-person-dash me-1"></i>Remove</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No approvers configured.</td></tr>@endforelse</tbody></table></div></div></div></div>
<div class="col-lg-4 mb-4"><div class="card"><div class="card-header bg-primary text-white"><h5 class="mb-0">Add Approver</h5></div><div class="card-body"><form action="{{ route('acl.add-approver') }}" method="POST">@csrf<div class="mb-3"><label class="form-label">User</label><select name="user_id" class="form-select" required><option value="">-- Select --</option>@foreach($availableUsers as $user)<option value="{{ $user->id }}">{{ $user->display_name ?? $user->username }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Min Level</label><select name="min_classification_level" class="form-select" required>@foreach($classifications as $cls)<option value="{{ $cls->level }}">{{ $cls->name }} (Level {{ $cls->level }})</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Max Level</label><select name="max_classification_level" class="form-select" required>@foreach($classifications as $cls)<option value="{{ $cls->level }}" @if($loop->last) selected @endif>{{ $cls->name }} (Level {{ $cls->level }})</option>@endforeach</select></div><div class="mb-3 form-check"><input type="hidden" name="email_notifications" value="0"><input type="checkbox" class="form-check-input" name="email_notifications" value="1" checked><label class="form-check-label">Email Notifications</label></div><button type="submit" class="btn btn-success w-100"><i class="bi bi-person-plus me-1"></i>Add Approver</button></form></div></div></div></div>
@endsection
