@extends('theme::layouts.1col')
@section('title', 'User Security Clearances')
@section('content')
<h1><i class="bi bi-people me-2"></i>User Security Clearances</h1>
<div class="row mb-4"><div class="col-md-8"><p class="text-muted">Manage security clearances for all users.</p></div><div class="col-md-4 text-end"><a href="{{ route('acl.groups') }}" class="btn btn-outline-secondary me-1"><i class="bi bi-arrow-left me-1"></i>Back to ACL</a><button class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#grantModal"><i class="bi bi-plus me-1"></i>Grant New Clearance</button></div></div>
@include('theme::partials.alerts')
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-bordered table-striped table-hover mb-0"><thead><tr><th>User</th><th>Clearance Level</th><th>Granted</th><th>Expires</th><th class="text-center">Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($clearances as $clr)
<tr><td><strong>{{ $clr->user_display_name ?? $clr->username ?? '-' }}</strong></td><td><span class="badge" style="background-color:{{ $clr->classification_color ?? '#6c757d' }};">{{ $clr->classification_name ?? '-' }}</span><br><small>Level {{ $clr->classification_level ?? '' }}</small></td><td>{{ $clr->granted_at ?? '-' }}</td><td>@if($clr->expires_at ?? null){{ $clr->expires_at }}@else<span class="text-muted">No expiry</span>@endif</td><td class="text-center"><span class="badge bg-success">Active</span></td><td class="text-end"><form action="{{ route('acl.set-clearance') }}" method="POST" class="d-inline" onsubmit="return confirm('Revoke clearance?');">@csrf<input type="hidden" name="user_id" value="{{ $clr->user_id ?? '' }}"><input type="hidden" name="classification_id" value="0"><button type="submit" class="btn btn-sm btn-outline-danger"><i class="bi bi-x-circle"></i></button></form></td></tr>
@empty
<tr><td colspan="6" class="text-center text-muted py-4">No user clearances assigned.</td></tr>
@endforelse
</tbody></table></div></div></div>
<div class="modal fade" id="grantModal" tabindex="-1"><div class="modal-dialog modal-lg"><form action="{{ route('acl.set-clearance') }}" method="POST">@csrf<div class="modal-content"><div class="modal-header"><h5 class="modal-title">Grant Security Clearance</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row"><div class="col-md-6 mb-3"><label class="form-label">User</label><select name="user_id" class="form-select" required><option value="">-- Select --</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->display_name ?? $user->username }}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label class="form-label">Clearance Level</label><select name="classification_id" class="form-select" required><option value="">-- Select --</option>@foreach($classifications as $cls)<option value="{{ $cls->id }}">{{ $cls->name }} (Level {{ $cls->level ?? '' }})</option>@endforeach</select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-success">Grant Clearance</button></div></div></form></div></div>
@endsection
