@extends('theme::layouts.1col')
@section('title', 'My Access Requests')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li><li class="breadcrumb-item active">My Access Requests</li></ol></nav>
@include('theme::partials.alerts')
<div class="card mb-4"><div class="card-header bg-primary text-white"><h5 class="mb-0"><i class="bi bi-shield-check me-2"></i>My Security Status</h5></div><div class="card-body"><div class="row"><div class="col-md-6"><p class="mb-1"><strong>Current Clearance Level:</strong></p>@if($currentClearance)<span class="badge fs-6" style="background-color:{{ $currentClearance->color ?? '#6c757d' }};">{{ e($currentClearance->classification_name) }}</span><small class="text-muted d-block mt-1">Granted: {{ $currentClearance->granted_at ? \Carbon\Carbon::parse($currentClearance->granted_at)->format('M j, Y') : '-' }}</small>@else<span class="badge bg-secondary fs-6">No Clearance</span>@endif</div></div></div></div>
@if($accessGrants->isNotEmpty())
<div class="card mb-4"><div class="card-header bg-primary text-white"><h5 class="mb-0"><i class="bi bi-key me-2"></i>My Access Grants</h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-bordered table-hover mb-0"><thead><tr><th>Object</th><th>Type</th><th>Access</th><th>Granted</th><th>Expires</th></tr></thead><tbody>@foreach($accessGrants as $grant)<tr><td><strong>{{ e($grant->object_title ?? 'Unknown') }}</strong></td><td><span class="badge bg-secondary">{{ ucfirst(str_replace('_', ' ', $grant->object_type ?? '')) }}</span></td><td><span class="badge bg-success">{{ ucfirst($grant->access_level ?? 'view') }}</span></td><td>{{ $grant->granted_at ? \Carbon\Carbon::parse($grant->granted_at)->format('M j, Y') : '-' }}<br><small class="text-muted">by {{ e($grant->granted_by_name ?? 'System') }}</small></td><td>@if($grant->expires_at){{ \Carbon\Carbon::parse($grant->expires_at)->format('M j, Y') }}@else<span class="text-muted">Never</span>@endif</td></tr>@endforeach</tbody></table></div></div></div>
@endif
<div class="card"><div class="card-header bg-primary text-white"><h5 class="mb-0"><i class="bi bi-clock-history me-2"></i>Request History</h5></div><div class="card-body p-0">@if($requests->isEmpty())<div class="p-4 text-center text-muted"><p>You haven't submitted any access requests yet.</p></div>@else<div class="table-responsive"><table class="table table-bordered table-hover mb-0"><thead><tr><th>Type</th><th>Requested</th><th>Status</th><th>Submitted</th></tr></thead><tbody>@foreach($requests as $req)<tr><td>{{ ucfirst($req->request_type ?? '-') }}</td><td><strong>{{ e($req->requested_classification ?? $req->justification ?? 'N/A') }}</strong></td><td>@php $statusColors = ['pending' => 'warning', 'approved' => 'success', 'denied' => 'danger']; @endphp<span class="badge bg-{{ $statusColors[$req->status ?? ''] ?? 'secondary' }}">{{ ucfirst($req->status ?? 'Pending') }}</span></td><td>{{ $req->created_at ? \Carbon\Carbon::parse($req->created_at)->format('M j, Y H:i') : '-' }}</td></tr>@endforeach</tbody></table></div>@endif</div></div>
@endsection
