@extends('theme::layouts.1col')
@section('title', 'Pending Access Requests')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li><li class="breadcrumb-item active">Access Requests</li></ol></nav>
@include('theme::partials.alerts')
<div class="row mb-4">
    <div class="col-md-3"><div class="card bg-warning text-dark"><div class="card-body text-center"><h2 class="mb-0">{{ $stats['pending'] }}</h2><small>Pending</small></div></div></div>
    <div class="col-md-3"><div class="card bg-success text-white"><div class="card-body text-center"><h2 class="mb-0">{{ $stats['approved_today'] }}</h2><small>Approved Today</small></div></div></div>
    <div class="col-md-3"><div class="card bg-danger text-white"><div class="card-body text-center"><h2 class="mb-0">{{ $stats['denied_today'] }}</h2><small>Denied Today</small></div></div></div>
    <div class="col-md-3"><div class="card bg-info text-white"><div class="card-body text-center"><h2 class="mb-0">{{ $stats['total_this_month'] }}</h2><small>This Month</small></div></div></div>
</div>
<div class="card"><div class="card-header bg-primary text-white"><h5 class="mb-0"><i class="bi bi-clipboard-check me-2"></i>Pending Access Requests</h5></div><div class="card-body p-0">@if($requests->isEmpty())<div class="p-4 text-center text-muted"><p>No pending requests. All caught up!</p></div>@else<div class="table-responsive"><table class="table table-bordered table-hover mb-0"><thead><tr><th>User</th><th>Classification</th><th>Urgency</th><th>Reason</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>@foreach($requests as $req)@php $urgency = strtolower($req->priority ?? 'normal'); @endphp<tr class="{{ $urgency === 'critical' ? 'table-danger' : ($urgency === 'high' ? 'table-warning' : '') }}"><td><strong>{{ e($req->user_name ?? $req->username ?? '-') }}</strong></td><td><span class="badge bg-primary">{{ e($req->classification_name ?? '-') }}</span></td><td><span class="badge bg-{{ match($urgency) { 'critical' => 'danger', 'high' => 'warning', default => 'secondary' } }}">{{ ucfirst($urgency) }}</span></td><td>{{ \Illuminate\Support\Str::limit($req->justification ?? '', 50) }}</td><td>{{ $req->created_at ? \Carbon\Carbon::parse($req->created_at)->format('M j, Y') : '-' }}</td><td><div class="btn-group btn-group-sm"><form action="{{ route('acl.review-request', ['id' => $req->id]) }}" method="POST" class="d-inline">@csrf<input type="hidden" name="decision" value="approved"><button type="submit" class="btn btn-outline-success"><i class="bi bi-check"></i></button></form><form action="{{ route('acl.review-request', ['id' => $req->id]) }}" method="POST" class="d-inline">@csrf<input type="hidden" name="decision" value="denied"><button type="submit" class="btn btn-outline-danger"><i class="bi bi-x"></i></button></form></div></td></tr>@endforeach</tbody></table></div>@endif</div></div>
@endsection
