@extends('theme::layouts.print')

@section('title', 'Finding Aid — ' . ($isadg['3.1.2']['value'] ?? 'Untitled'))

@section('content')
<div class="finding-aid">
    <header class="text-center mb-4 pb-3 border-bottom">
        <h1 class="h2">{{ $isadg['3.1.2']['value'] ?? 'Untitled' }}</h1>
        <p class="text-muted">
            Finding Aid
            @if(!empty($isadg['3.1.1']['value']))
                &mdash; {{ $isadg['3.1.1']['value'] }}
            @endif
        </p>
        <p class="small text-muted">
            Generated by OpenRiC on {{ now()->format('j F Y') }}
        </p>
    </header>

    {{-- Identity Statement Area --}}
    <section class="mb-4">
        <h2 class="h4 border-bottom pb-1 mb-3">Identity Statement Area</h2>
        <table class="table table-sm">
            <tbody>
                @foreach(['3.1.1', '3.1.2', '3.1.3', '3.1.4', '3.1.5'] as $code)
                    @if(!empty($isadg[$code]['value']))
                        <tr>
                            <th style="width:35%;">{{ $isadg[$code]['label'] }}</th>
                            <td>{{ $isadg[$code]['value'] }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </section>

    {{-- Context Area --}}
    <section class="mb-4">
        <h2 class="h4 border-bottom pb-1 mb-3">Context Area</h2>
        @if(count($creators) > 0)
            <p><strong>Creator(s):</strong>
                @foreach($creators as $creator)
                    {{ $creator['name']['value'] ?? $creator['agent']['value'] ?? 'Unknown' }}@if(!$loop->last); @endif
                @endforeach
            </p>
        @endif
        <table class="table table-sm">
            <tbody>
                @foreach(['3.2.2', '3.2.3', '3.2.4'] as $code)
                    @if(!empty($isadg[$code]['value']))
                        <tr>
                            <th style="width:35%;">{{ $isadg[$code]['label'] }}</th>
                            <td>{{ $isadg[$code]['value'] }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </section>

    {{-- Content and Structure Area --}}
    <section class="mb-4">
        <h2 class="h4 border-bottom pb-1 mb-3">Content and Structure Area</h2>
        <table class="table table-sm">
            <tbody>
                @foreach(['3.3.1', '3.3.2', '3.3.3', '3.3.4'] as $code)
                    @if(!empty($isadg[$code]['value']))
                        <tr>
                            <th style="width:35%;">{{ $isadg[$code]['label'] }}</th>
                            <td>{{ $isadg[$code]['value'] }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </section>

    {{-- Conditions of Access and Use Area --}}
    <section class="mb-4">
        <h2 class="h4 border-bottom pb-1 mb-3">Conditions of Access and Use</h2>
        <table class="table table-sm">
            <tbody>
                @foreach(['3.4.1', '3.4.2', '3.4.3', '3.4.4', '3.4.5'] as $code)
                    @if(!empty($isadg[$code]['value']))
                        <tr>
                            <th style="width:35%;">{{ $isadg[$code]['label'] }}</th>
                            <td>{{ $isadg[$code]['value'] }}</td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </section>

    {{-- Allied Materials Area --}}
    @php
        $hasAllied = false;
        foreach(['3.5.1', '3.5.2', '3.5.3', '3.5.4'] as $c) {
            if (!empty($isadg[$c]['value'])) { $hasAllied = true; break; }
        }
    @endphp
    @if($hasAllied)
        <section class="mb-4">
            <h2 class="h4 border-bottom pb-1 mb-3">Allied Materials</h2>
            <table class="table table-sm">
                <tbody>
                    @foreach(['3.5.1', '3.5.2', '3.5.3', '3.5.4'] as $code)
                        @if(!empty($isadg[$code]['value']))
                            <tr>
                                <th style="width:35%;">{{ $isadg[$code]['label'] }}</th>
                                <td>{{ $isadg[$code]['value'] }}</td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        </section>
    @endif

    {{-- Notes --}}
    @if(!empty($isadg['3.6.1']['value']))
        <section class="mb-4">
            <h2 class="h4 border-bottom pb-1 mb-3">Notes</h2>
            <p>{{ $isadg['3.6.1']['value'] }}</p>
        </section>
    @endif

    {{-- Hierarchical contents listing --}}
    @if(!empty($tree['children']))
        <section class="mb-4">
            <h2 class="h4 border-bottom pb-1 mb-3">Contents</h2>
            @include('record-manage::finding-aid._print_tree', ['nodes' => $tree['children'], 'depth' => 0])
        </section>
    @endif

    <footer class="mt-5 pt-3 border-top text-center text-muted small">
        <p>Generated from RiC-O triplestore by OpenRiC &mdash; {{ config('app.url') }}</p>
        <p>Standards: ISAD(G) 2nd Edition, rendered from RiC-O 1.1 triples</p>
    </footer>
</div>
@endsection
